# Generated by Django 3.0.5 on 2020-04-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('currency', models.CharField(choices=[('PHP', 'PHP'), ('USD', 'USD'), ('CAD', 'CAD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('AUD', 'AUD')], max_length=3)),
                ('tithe', models.FloatField(default=None, null=True)),
                ('offering', models.FloatField(default=None, null=True)),
                ('firstfruit', models.FloatField(default=None, null=True)),
                ('mission', models.FloatField(default=None, null=True)),
                ('care', models.FloatField(default=None, null=True)),
                ('ladies', models.FloatField(default=None, null=True)),
                ('men', models.FloatField(default=None, null=True)),
                ('youth', models.FloatField(default=None, null=True)),
                ('choir', models.FloatField(default=None, null=True)),
                ('prayer_breakfast', models.FloatField(default=None, null=True)),
                ('circle_of_faith', models.FloatField(default=None, null=True)),
                ('creative_team', models.FloatField(default=None, null=True)),
                ('dvbs', models.FloatField(default=None, null=True)),
                ('prison_ministry', models.FloatField(default=None, null=True)),
                ('others', models.FloatField(default=None, null=True)),
                ('others_description', models.CharField(max_length=50, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Member')),
            ],
        ),
    ]
