# Generated by Django 3.0.5 on 2020-04-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200412_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='firstfruit_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='input_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
