# Generated by Django 3.0.5 on 2020-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200412_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.CharField(choices=[('Worship', 'Worship'), ('Gospel', 'Gospel'), ('Prayer', 'Prayer'), ('Other', 'Other')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
