# Generated by Django 3.0.5 on 2020-04-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('serial', models.CharField(max_length=50, null=True)),
                ('amount', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('others', 'others'), ('allowances', 'allowances'), ('utilities', 'utilities'), ('cash advance', 'cash advance'), ('mission', 'mission'), ('care', 'care'), ('ladies', 'ladies'), ('men', 'men'), ('ladies', 'ladies'), ('youth', 'youth'), ('prayer_breakfast', 'prayer_breakfast'), ('circle_of_faith', 'circle_of_faith'), ('creative_team', 'creative_team'), ('dvbs', 'dvbs'), ('prison_ministry', 'prison_ministry'), ('tithe', 'tithe'), ('offering', 'offering'), ('firstfruit', 'firstfruit')], max_length=20, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Member')),
            ],
        ),
    ]
