# Generated by Django 3.0.5 on 2020-04-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bdate',
            field=models.DateTimeField(null=True),
        ),
    ]
