# Generated by Django 3.0.5 on 2020-04-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20200412_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_member',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1, null=True),
        ),
    ]
