# Generated by Django 3.0.5 on 2020-04-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_member_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='civilstatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_member',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1, null=True),
        ),
    ]
