# Generated by Django 3.0.5 on 2020-04-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20200412_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_baptized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_marriage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_salvation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
